In [ ]:
1. Create a null vector of size 10 but the fifth value which is 1.

In [2]:
import numpy as np
null_vector = np.zeros(10)
null_vector[4] = 1
null_vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [ ]:
2. Create a vector with values ranging from 10 to 49.

In [3]:
vector = np.arange(10,50)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [ ]:
3. Create a 3x3 matrix with values ranging from 0 to 8.

In [5]:
mat = np.random.randint(0,9,(3,3))
mat

array([[3, 0, 2],
       [4, 0, 0],
       [6, 2, 4]])

In [ ]:
4. Find indices of non-zero elements from [1,2,0,0,4,0].

In [6]:
arr = np.array([1,2,0,0,4,0])
index = np.nonzero(arr)
index

(array([0, 1, 4], dtype=int64),)

In [ ]:
5. Create a 10x10 array with random values and find the minimum and maximum values.

In [34]:
arr1 = np.random.seed(8)
arr1 = np.random.randint(0,100,(10,10))
print(arr1)
print("Minimum value",arr1.min())
print("Maximum value",arr1.max())

[[67 84  5 90  8 83 63 48 85 60]
 [49 74 27 13  9 61 15 93 98 59]
 [18 14 93 56  9 51 68 53 53 71]
 [59 42 26 66  9 81 15 92 91 63]
 [86 31 20 45 21 72 92 28 95 47]
 [10 64  7 45  2 38 71 95 36 89]
 [60 91 68 37 66 82 38 54 86 39]
 [46  6 95 32 73 98  7  9 98 42]
 [19 59 48  9 16 78 55 55 20 98]
 [87 98 24  6 28  5 66 19 99 75]]
Minimum value 2
Maximum value 99


In [ ]:
6. Create a random vector of size 30 and find the mean value.

In [40]:
rand_vec = np.arange(30,54)
print(rand_vec)
rand_vec.mean()

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53]


41.5